### PR TITLE
chore: Update fixpack to fixed version

### PR DESCRIPTION
**Pull request by pke**
See https://github.com/HenrikJoreteg/fixpack/issues/31

### CODE REVIEW

**Comment by niftylettuce** [comment]
This isn't a security vulnerability...

**Comment by pke** [comment]
I trusted GH and npm audit on this? Why you think its not?

**Comment by niftylettuce** [comment]
because we aren't exposing this to a third party or for injection or anything remotely close to that

half of the security vulnerabilities published are a joke

**Comment by pke** [comment]
Oh ok, so do you want to dismiss the security warnings on all cabinjs repos?
Should I revert this patch then? I just saw I also forgot to update the `yarn.lock` file anyway.

**Comment by niftylettuce** [comment]
don't worry about it 😄 it's fine to leave as is

**Comment by pke** [comment]
But update the `yarn.lock` file?

**Comment by niftylettuce** [comment]
naw don't worry about it - next time I add more fields and have to republish I will update it

**Pull request merged**
